export default {
  label: '标题',
  text: '文本',
  number: '数字',
  textarea: '长文本',
  radio: '单选',
  select: '选择',
  checkbox: '复选',
  boolean: '是否',
  region: '地区',
  object: '对象',
  array: '数组',
  nation: '民族',
  date: '日期',
  year: '年份',
  month: '月份',
  datetime: '日期时间',
  time: '时间',
};
